name: Run Bot

on:
  schedule:
    - cron: "0 */3 * * *"  # This cron expression runs the job every 3 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Create .env file
        run: |
          echo "COIN_STATS_API_KEY=${{ secrets.COIN_STATS_API_KEY }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET_KEY=${{ secrets.TWITTER_API_SECRET_KEY }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> .env

      - name: Build the application
        run: go build -o DegenAIBot

      - name: Run the bot
        run: ./DegenAIBot